<?php

return [
    'scanner_issue' => [
        'label' => 'Scanner issue',
        'description' => 'Battery, login, pairing, or connection problem.',
        'requester_roles' => ['employee', 'manager', 'ops_manager', 'hr', 'admin'],
        'category_names' => ['IT Support', 'Operations'],
        'default_priority' => 'medium',
        'title' => 'Scanner issue at station',
        'description_template' => 'Scanner problem observed. Device is not working as expected and is blocking task progress.',
        'location_label' => 'Station / area',
        'detail_prompts' => [
            'Asset tag or scanner ID',
            'What the device is doing now',
            'Whether work is fully blocked',
        ],
        'evidence_hint' => 'Attach a photo or screenshot if the device shows an error code.',
    ],
    'safety_hazard' => [
        'label' => 'Safety concern',
        'description' => 'Hazard, spill, blocked path, or damaged equipment.',
        'requester_roles' => ['employee', 'manager', 'ops_manager', 'hr', 'admin'],
        'category_names' => ['Safety', 'Operations'],
        'default_priority' => 'high',
        'title' => 'Safety concern in work area',
        'description_template' => 'Safety concern observed. Immediate risk and impact need review.',
        'location_label' => 'Affected area',
        'detail_prompts' => [
            'What the hazard is',
            'Whether work can continue safely',
            'Who is affected right now',
        ],
        'evidence_hint' => 'Attach a photo if it is safe to do so.',
    ],
    'facilities_issue' => [
        'label' => 'Facilities issue',
        'description' => 'Door, lighting, printer, workstation, or canteen issue.',
        'requester_roles' => ['employee', 'manager', 'ops_manager', 'hr', 'admin'],
        'category_names' => ['Facilities', 'Operations'],
        'default_priority' => 'medium',
        'title' => 'Facilities issue affecting work area',
        'description_template' => 'Facilities issue observed. The problem is affecting normal work or access.',
        'location_label' => 'Affected area',
        'detail_prompts' => [
            'What is broken or unavailable',
            'Whether there is a workaround',
            'How many people are affected',
        ],
        'evidence_hint' => 'Attach a photo if the damage or fault is visible.',
    ],
    'transport_issue' => [
        'label' => 'Transport problem',
        'description' => 'Bus, shuttle, parking, or route disruption.',
        'requester_roles' => ['employee', 'manager', 'ops_manager', 'hr', 'admin'],
        'category_names' => ['Transport'],
        'default_priority' => 'medium',
        'title' => 'Transport problem for shift travel',
        'description_template' => 'Transport issue observed. Include route, stop, and impact on arrival or departure.',
        'location_label' => 'Bus stop / route',
        'detail_prompts' => [
            'Route or shuttle number',
            'Stop or pickup point',
            'Whether service was late, missing, or full',
        ],
        'evidence_hint' => 'Attach a screenshot or photo if it helps explain the disruption.',
    ],
    'missed_punch' => [
        'label' => 'Missed punch',
        'description' => 'Clock-in or clock-out correction request.',
        'requester_roles' => ['employee', 'manager', 'ops_manager', 'hr', 'admin'],
        'category_names' => ['HR'],
        'default_priority' => 'low',
        'title' => 'Missed punch correction request',
        'description_template' => 'Missed punch needs review. Include shift date, expected time, and whether the missing event is clock-in, clock-out, or both.',
        'location_label' => 'Clock station / area',
        'detail_prompts' => [
            'Shift date',
            'Expected clock time',
            'Whether manager has already been informed',
        ],
        'evidence_hint' => 'Attach a screenshot or photo of any supporting time record if available.',
        'approval_steps' => [
            [
                'step_key' => 'hr_review',
                'approver_role' => 'hr',
                'requester_status' => 'Awaiting HR review',
            ],
        ],
    ],
    'shift_swap_request' => [
        'label' => 'Shift swap request',
        'description' => 'Request approval for a shift exchange.',
        'requester_roles' => ['employee', 'manager', 'ops_manager', 'hr', 'admin'],
        'category_names' => ['HR'],
        'default_priority' => 'low',
        'title' => 'Shift swap approval request',
        'description_template' => 'Shift swap request needs review. Include the shift date, the swap partner if known, and whether the manager has already been informed.',
        'location_label' => 'Department / shift',
        'detail_prompts' => [
            'Current shift date and time',
            'Requested replacement shift',
            'Swap partner name or employee ID',
        ],
        'evidence_hint' => 'Attach a screenshot if there is a documented agreement or schedule reference.',
        'approval_steps' => [
            [
                'step_key' => 'manager_review',
                'approver_role' => 'manager',
                'requester_status' => 'Awaiting manager approval',
            ],
            [
                'step_key' => 'hr_review',
                'approver_role' => 'hr',
                'requester_status' => 'Awaiting weekday HR review',
            ],
        ],
    ],
    'report_on_behalf' => [
        'label' => 'Report on behalf',
        'description' => 'Manager creates a ticket for an employee blocker or repeated issue.',
        'requester_roles' => ['manager', 'ops_manager', 'hr', 'admin'],
        'category_names' => ['Operations', 'Facilities', 'IT Support', 'HR', 'Safety'],
        'default_priority' => 'medium',
        'title' => 'Operational issue reported on behalf of employee',
        'description_template' => 'Manager reporting on behalf of an employee. Summarise the blocker, affected employee or area, and the operational impact.',
        'location_label' => 'Affected area',
        'detail_prompts' => [
            'Affected employee or group',
            'Operational impact',
            'Immediate workaround in place',
        ],
        'evidence_hint' => 'Attach a photo, screenshot, or supporting note if available.',
    ],
    'department_blocker' => [
        'label' => 'Department blocker',
        'description' => 'Manager escalation for a wider operational issue affecting a department or shift.',
        'requester_roles' => ['manager', 'ops_manager', 'hr', 'admin'],
        'category_names' => ['Operations', 'Facilities', 'IT Support'],
        'default_priority' => 'high',
        'title' => 'Department blocker requiring escalation',
        'description_template' => 'Department-level blocker needs escalation. Summarise what is blocked, how many associates are affected, and what workaround is currently in place.',
        'location_label' => 'Department / area',
        'detail_prompts' => [
            'Affected headcount',
            'Blocked process or station',
            'Whether work can continue in a reduced mode',
        ],
        'evidence_hint' => 'Attach evidence that helps triage the operational impact quickly.',
    ],
];
